### ISSUE TITLE
Notifications are confusing

### ISSUE THREAD

**Issue by MatejKovacic** [USBGuard/usbguard#203]
I have found that noticifations for new devices (in Qt applet) are a little bit weird. Actually, their timing is not correct.

Scenario:
1. user inserts new device.
2. USBguard opens new window asking what to do.
3. First notification appears: "usb device inserted"
4. User allows the device.
5. First notification expires, and second is displayed "usb device blocked"
6. After some time, second notification expires and third appears: "usb device allowed".

You see, the problem is, that second notification appears after user already allowed the device, which is confusing.

My suggestion is to unite several notifications to one group. For instance:
"USB device inserted. Device is temporarily blocked".
"USB device inserted. Device is blocked/allowed".
"New rule set for device. Device is blocked/allowed".

And, notification should expire as soon as user does his action (click block or allow).

**Comment by BenjaminSchubert** [comment]
I'm currently working on a rework of the GUI, thanks for the feedback !

This should get fixed by my new version, I don't have enough time to finish it these days however, sorry.

If you want to give it a try, please see PR https://github.com/dkopecek/usbguard/pull/186 . I'd be happy to incorporate more feedback.
